AppBundle\Entity\User:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\UserRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        firstname:
            type: string
            length: 255
        surname:
            type: string
            length: 255
        email:
            type: string
            length: 255
            unique: true
        passwordHash:
            type: string
            length: '512'
        isActive:
            type: boolean
    lifecycleCallbacks: {  }
